# set version as running build number for CI build use
version: Build {build}

configuration: Release

os: Visual Studio 2017

skip_tags: true

environment:
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  marten_testing_database: "Host=localhost;Port=5432;Database=marten_test;Username=postgres;Password=Password12!"
  POSTGRES_PATH: C:\Program Files\PostgreSQL\9.5
  PG_PLV8_EXTENSION_ZIP_FILENAME: pg95plv8jsbin_w64
  PG_DB: marten_test

services: 
  - postgresql95

install:
  - set PATH=C:\Ruby%RUBY_VERSION%\bin;%PATH%
  - ruby --version
  - gem install bundler --conservative
  - bundle config --local path vendor/bundle
  - bundle install
  - SET PATH=%POSTGRES_PATH%\bin;%PATH%
  - curl -L -O -S -s http://www.postgresonline.com/downloads/%PG_PLV8_EXTENSION_ZIP_FILENAME%.zip
  - 7z x %PG_PLV8_EXTENSION_ZIP_FILENAME%.zip
  - xcopy /s /y /d %PG_PLV8_EXTENSION_ZIP_FILENAME% "%POSTGRES_PATH%\"

before_build:
  - SET PGUSER=postgres
  - SET PGPASSWORD=Password12!
  - createdb %PG_DB%
  - psql -d %PG_DB% -c "create extension if not exists plv8;"
  - npm install
  - dotnet --info

build_script:
- cmd: >-
    rake ci
test: off

artifacts:
  - path: '**\Marten.*.nupkg' # find all NuGet packages recursively